const emptyCopy = {
  pages: "No page-level UI changes detected yet.",
  behaviors: "No e2e behavior changes detected yet.",
  designSystem: "No design system changes detected yet.",
  backend: "No backend implementation changes detected yet.",
  database: "No database or migration changes detected yet.",
  protos: "No proto contract changes detected yet.",
};

export function buildDeck(context) {
  const generatedAt = normalizeDate(context.generatedAt);
  const sections = normalizeSections(context.sections);
  const changedFiles = context.changedFiles ?? [];
  const featureItems = featureItemsFromBehaviors(sections.behaviors);

  return [
    "---",
    "title: " + yamlString(context.title),
    "info: Generated by backbone pr-slide.",
    "drawings:",
    "  persist: false",
    "transition: slide-left",
    "---",
    "",
    retroStyles(),
    "",
    `<section class="retro-stage title-stage">`,
    `<div class="stamp">Prepared for the Review Committee</div>`,
    `<div class="paperclip">📎</div>`,
    `<div class="memo-window">`,
    `<div class="win95-titlebar"><span>WINDOW 3.1-ish PR_BRIEF.EXE</span><span>□ ×</span></div>`,
    `<div class="memo-body">`,
    `<p class="kicker">Backbone corporate intranet transmission</p>`,
    `<h1>${escapeHtml(context.title)}</h1>`,
    `<p class="purpose">${escapeHtml(catchyPurpose(context.purpose))}</p>`,
    `<div class="floppy-label">💾 ${escapeHtml(context.branch)} -> ${escapeHtml(context.base)} · ${generatedAt}</div>`,
    `</div>`,
    `</div>`,
    `</section>`,
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    `<div class="retro-stage split-stage">`,
    `<div>`,
    `<p class="kicker">Quarterly roadmap energy</p>`,
    `<h1>Pull Request Overview</h1>`,
    `<p class="big-promise">${escapeHtml(catchyPurpose(context.purpose))}</p>`,
    `</div>`,
    `<div class="office-oracle">`,
    `<div class="oracle-face">📎</div>`,
    `<div class="speech-bubble">I see changed files. I also see feelings.</div>`,
    `<div class="tiny-caption">CLIPPY-ADJACENT HELPER, LEGALLY DISTINCT</div>`,
    `</div>`,
    `</div>`,
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## User-Facing Page Changes",
    "",
    `<div class="slide-subtitle">What pages changed and what they help users accomplish.</div>`,
    "",
    formatWindowItems(sections.pages, emptyCopy.pages, {
      icon: "🖥️",
      sticker: "ROUTE",
      emptyIcon: "📠",
    }),
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## Features",
    "",
    `<div class="slide-subtitle">Product capabilities described by the end-to-end specifications.</div>`,
    "",
    formatFeatureOverview(featureItems, emptyCopy.behaviors),
    "",
    ...formatFeatureSlides(featureItems),
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## Design System Updates",
    "",
    `<div class="slide-subtitle">Reusable UI components, stories, and interaction states updated by this PR.</div>`,
    "",
    formatStickerItems(sections.designSystem, emptyCopy.designSystem),
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    `<div class="retro-stage basement-title">`,
    `<div class="warning-sign">⚠</div>`,
    `<h1>Technical Implementation</h1>`,
    `<p>Contracts, data, and backend services that support the user-facing changes.</p>`,
    `</div>`,
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## API Contract Changes",
    "",
    formatApiOverview(sections.protos, emptyCopy.protos),
    "",
    ...formatProtoServiceSlides(sections.protos),
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## Database And Persistence Changes",
    "",
    formatDatabaseOverview(sections.database, emptyCopy.database),
    "",
    ...formatMigrationSlides(sections.database),
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## Backend And Integration Changes",
    "",
    formatWindowItems(sections.backend, emptyCopy.backend, {
      icon: "🖧",
      sticker: "BACKEND",
      emptyIcon: "🔌",
    }),
    "",
    "---",
    "class: retro-slide",
    "---",
    "",
    "## Review Evidence",
    "",
    `<div class="slide-subtitle">Changed files used to generate this presentation.</div>`,
    "",
    formatFiles(changedFiles),
    "",
  ].join("\n");
}

export function classifyChangedFiles(changedFiles) {
  const sections = normalizeSections({});

  for (const file of changedFiles) {
    const item = {
      label: humanizeFile(file),
      detail: file,
    };

    if (isProto(file)) {
      sections.protos.push(item);
    }

    if (isDatabase(file)) {
      sections.database.push(item);
    }

    if (isBehavior(file)) {
      sections.behaviors.push({
        label: catchyBehaviorLabel(file),
        detail: file,
      });
    }

    if (isDesignSystem(file)) {
      sections.designSystem.push(item);
    }

    if (isPage(file)) {
      sections.pages.push(item);
    }

    if (isBackend(file)) {
      sections.backend.push(item);
    }
  }

  return sections;
}

export function inferPurpose(changedFiles) {
  if (changedFiles.length === 0) {
    return "This PR is ready to be narrated once branch changes are available.";
  }

  const sections = classifyChangedFiles(changedFiles);
  const visibleCount =
    sections.pages.length + sections.behaviors.length + sections.designSystem.length;
  const technicalCount =
    sections.backend.length + sections.database.length + sections.protos.length;

  if (visibleCount > 0 && technicalCount > 0) {
    return "This PR connects product-facing polish with the backend contracts that make it real.";
  }

  if (visibleCount > 0) {
    return "This PR sharpens what users see and protects the behavior reviewers care about.";
  }

  return "This PR improves the technical foundation while keeping reviewer attention on the important moving parts.";
}

function normalizeSections(sections) {
  return {
    pages: sections.pages ?? [],
    behaviors: sections.behaviors ?? [],
    designSystem: sections.designSystem ?? [],
    backend: sections.backend ?? [],
    database: sections.database ?? [],
    protos: sections.protos ?? [],
  };
}

function formatWindowItems(items, emptyText, options) {
  if (items.length === 0) {
    return emptyDesk(emptyText, options.emptyIcon);
  }

  return prioritizeItems(items)
    .slice(0, 6)
    .map(
      (item) => cardHtml(item, options),
    )
    .join("\n\n");
}

function cardHtml(item, options) {
  return `<div class="win95-window evidence-window"><div class="win95-titlebar"><span>${options.icon} ${escapeHtml(item.label)}</span><span>□ ×</span></div><div class="window-body"><div class="sticker">${options.sticker}</div>${formatScreenshot(item)}<p>${escapeHtml(item.detail || "Reviewer-visible change detected.")}</p><div class="evidence">Evidence: <code>${escapeHtml(item.detail || item.label)}</code></div></div></div>`;
}

function formatApiOverview(items, emptyText) {
  const services = protoServices(items);

  if (services.length === 0) {
    return emptyDesk(emptyText, "📄");
  }

  return `<div class="feature-overview">${services
    .map(
      ({ item, service }) =>
        `<div class="feature-summary-card"><span class="feature-badge">SERVICE</span><strong>${escapeHtml(service.name)}</strong><span>${service.rpcs.length} RPC${service.rpcs.length === 1 ? "" : "s"} in ${escapeHtml(item.detail)}</span></div>`,
    )
    .join("")}</div>`;
}

function formatProtoServiceSlides(items) {
  return protoServices(items).flatMap(({ item, service }) => [
    "---",
    "class: retro-slide",
    "---",
    "",
    `## ${escapeHtml(service.name)}`,
    "",
    `<div class="slide-subtitle">This service exposes the application contract used by the frontend.</div>`,
    "",
    `<div class="win95-window evidence-window"><div class="win95-titlebar"><span>📡 RPC service</span><span>□ ×</span></div><div class="window-body"><div class="sticker">PROTO</div><p>We added this service with these RPCs:</p><ul>${service.rpcs
      .map(
        (rpc) =>
          `<li><strong>${escapeHtml(rpc.name)}</strong>: ${escapeHtml(rpc.description)}</li>`,
      )
      .join("")}</ul><div class="evidence">Evidence: <code>${escapeHtml(item.detail)}</code></div></div></div>`,
    "",
  ]);
}

function protoServices(items) {
  return prioritizeItems(items).flatMap((item) =>
    (item.protoServices ?? []).map((service) => ({ item, service })),
  );
}

function formatDatabaseOverview(items, emptyText) {
  const migrations = migrationItems(items);

  if (migrations.length === 0) {
    return emptyDesk(emptyText, "🗂️");
  }

  return `<div class="feature-overview">${migrations
    .map(
      (item) =>
        `<div class="feature-summary-card"><span class="feature-badge">MIGRATION</span><strong>${escapeHtml(item.label)}</strong><span>${escapeHtml((item.migrationSummary ?? [item.detail])[0])}</span></div>`,
    )
    .join("")}</div>`;
}

function formatMigrationSlides(items) {
  return migrationItems(items).flatMap((item) => [
    "---",
    "class: retro-slide",
    "---",
    "",
    `## ${escapeHtml(item.label)}`,
    "",
    `<div class="slide-subtitle">Database migration applied by this PR.</div>`,
    "",
    `<div class="win95-window evidence-window"><div class="win95-titlebar"><span>🗄️ Migration</span><span>□ ×</span></div><div class="window-body"><div class="sticker">DB</div><p>This migration changes the database as follows:</p><ul>${(item.migrationSummary ?? [item.detail])
      .map((summary) => `<li>${escapeHtml(summary)}</li>`)
      .join("")}</ul><div class="evidence">Evidence: <code>${escapeHtml(item.detail)}</code></div></div></div>`,
    "",
  ]);
}

function migrationItems(items) {
  return prioritizeItems(items).filter(
    (item) => item.detail?.includes("/migrations/") && item.detail.endsWith(".sql"),
  );
}

function formatBehaviorItems(items, emptyText) {
  return formatFeatureOverview(featureItemsFromBehaviors(items), emptyText);
}

function formatFeatureOverview(items, emptyText) {
  if (items.length === 0) {
    return emptyDesk(emptyText, "✅");
  }

  return `<div class="feature-overview">
${items
  .slice(0, 6)
  .map(
    (item) => `<div class="feature-summary-card">
  <span class="feature-badge">FEATURE</span>
  <strong>${escapeHtml(item.label)}</strong>
  <span>${escapeHtml(item.summary)}</span>
</div>`,
  )
  .join("\n")}
</div>`;
}

function formatFeatureSlides(items) {
  return items
    .slice(0, 6)
    .flatMap((item) => [
      "---",
      "class: retro-slide",
      "---",
    "",
    `## ${escapeHtml(item.label)}`,
    "",
    `<div class="slide-subtitle">${escapeHtml(item.summary)}</div>`,
    "",
    `<div class="win95-window evidence-window feature-window"><div class="win95-titlebar"><span>✨ Feature specification</span><span>□ ×</span></div><div class="window-body"><div class="sticker">FEATURE</div>${formatScreenshot(item)}<p>${escapeHtml(item.description)}</p><div class="evidence">Evidence: <code>${escapeHtml(item.detail || item.label)}</code></div></div></div>`,
      "",
    ]);
}

function featureItemsFromBehaviors(items) {
  const featureItems = prioritizeItems(items).filter((item) =>
    item.detail?.startsWith("e2e/features/"),
  );

  const sourceItems = featureItems.length > 0 ? featureItems : prioritizeItems(items);

  return sourceItems.map((item) => {
    const feature = featureCopy(item);

    return {
      ...item,
      label: feature.label,
      summary: feature.summary,
      description: feature.description,
    };
  });
}

function featureCopy(item) {
  const detail = item.detail ?? "";
  const key = detail
    .split("/")
    .at(-1)
    ?.replace(/\.feature$/, "");

  if (key === "helloworld") {
    return {
      label: "Say hello through the UI",
      summary: "Users can submit a name and see the server-generated greeting.",
      description:
        "The hello-world flow proves the browser, ConnectRPC, Rust server, and SQLite persistence path work together.",
    };
  }

  return {
    label: item.label.replace(/: the user promise$/, ""),
    summary: item.detail || "A user-facing capability is described by the e2e specification.",
    description: item.detail || "This feature is included in the end-to-end product specification.",
  };
}

function formatStickerItems(items, emptyText) {
  if (items.length === 0) {
    return emptyDesk(emptyText, "🏷️");
  }

  return `<div class="sticker-sheet">
${prioritizeItems(items)
  .slice(0, 10)
  .map(
    (item) =>
      `<div class="component-sticker"><div class="sticker-emoji">🏷️</div>${formatScreenshot(item)}<strong>${escapeHtml(item.label)}</strong><span>${escapeHtml(item.detail || "Component evidence")}</span></div>`,
  )
  .join("\n")}
</div>`;
}

function prioritizeItems(items) {
  return [...items].sort((left, right) => {
    const imageScore = Number(Boolean(right.image)) - Number(Boolean(left.image));

    if (imageScore !== 0) {
      return imageScore;
    }

    const featureScore =
      Number(right.detail?.startsWith("e2e/features/")) -
      Number(left.detail?.startsWith("e2e/features/"));

    if (featureScore !== 0) {
      return featureScore;
    }

    return 0;
  });
}

function formatScreenshot(item) {
  if (!item.image) {
    return "";
  }

  return `<img class="deck-screenshot" src="${escapeHtml(item.image)}" alt="${escapeHtml(item.label)} screenshot" />`;
}

function formatInlineScreenshot(item) {
  if (!item.image) {
    return "";
  }

  return `<img class="journey-screenshot" src="${escapeHtml(item.image)}" alt="${escapeHtml(item.label)} screenshot" />`;
}

function emptyDesk(emptyText, icon) {
  return `<div class="empty-desk">
  <div class="empty-icon">${icon}</div>
  <strong>${escapeHtml(emptyText)}</strong>
  <span>The office has logged zero incidents in this bucket.</span>
</div>`;
}

function formatFiles(files) {
  if (files.length === 0) {
    return emptyDesk("No focused changed-file list was provided.", "🧾");
  }

  return `<div class="evidence-grid">
${files.map((file) => `<code>${escapeHtml(file)}</code>`).join("\n")}
</div>`;
}

function catchyPurpose(purpose) {
  const trimmed = purpose.trim();

  if (trimmed.endsWith(".")) {
    return trimmed;
  }

  return trimmed + ".";
}

function yamlString(value) {
  return JSON.stringify(value);
}

function normalizeDate(value) {
  const date = value instanceof Date ? value : new Date(value);

  return date.toISOString().slice(0, 10);
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function retroStyles() {
  return `<style>
:root {
  --bb-cream: #fff7d6;
  --bb-paper: #fffce8;
  --bb-ink: #171129;
  --bb-cyan: #00d5ff;
  --bb-pink: #ff4fd8;
  --bb-purple: #6f42ff;
  --bb-yellow: #ffe66d;
  --bb-green: #3dfc89;
  --bb-shadow: rgba(23, 17, 41, 0.35);
}

.slidev-layout {
  color: var(--bb-ink);
  background:
    linear-gradient(135deg, rgba(255, 79, 216, 0.18), rgba(0, 213, 255, 0.22)),
    linear-gradient(45deg, rgba(255,255,255,.18) 25%, transparent 25% 50%, rgba(255,255,255,.18) 50% 75%, transparent 75%);
  background-size: auto, 28px 28px;
}

.retro-stage {
  min-height: 100%;
  position: relative;
  display: grid;
  place-items: center;
  padding: 42px;
}

.title-stage {
  background: radial-gradient(circle at 15% 20%, #fff 0 0.5rem, transparent 0.55rem), linear-gradient(135deg, #2cf6ff, #ff7ae6 54%, #ffe66d);
}

.memo-window,
.win95-window {
  background: var(--bb-paper);
  border: 4px solid var(--bb-ink);
  box-shadow: 10px 10px 0 var(--bb-shadow);
}

.memo-window {
  width: min(860px, 92%);
  transform: rotate(-1deg);
}

.win95-titlebar {
  display: flex;
  justify-content: space-between;
  gap: 24px;
  background: linear-gradient(90deg, #1b2cff, #c600ff);
  color: white;
  font-family: "Courier New", monospace;
  font-size: 15px;
  font-weight: 800;
  padding: 8px 12px;
  text-transform: uppercase;
}

.memo-body {
  padding: 38px;
}

.kicker,
.tiny-caption,
.evidence {
  font-family: "Courier New", monospace;
  text-transform: uppercase;
  letter-spacing: 0;
}

.kicker {
  color: #6f42ff;
  font-weight: 900;
}

.purpose,
.big-promise {
  font-size: 30px;
  line-height: 1.15;
}

.floppy-label,
.stamp,
.sticker,
.promise-stamp {
  display: inline-block;
  border: 3px solid var(--bb-ink);
  background: var(--bb-yellow);
  box-shadow: 4px 4px 0 var(--bb-ink);
  font-family: "Courier New", monospace;
  font-weight: 900;
  padding: 8px 12px;
}

.stamp {
  position: absolute;
  top: 30px;
  right: 42px;
  transform: rotate(5deg);
  color: #d10072;
}

.paperclip {
  position: absolute;
  left: 40px;
  bottom: 30px;
  font-size: 72px;
  animation: officeFloat 3.5s ease-in-out infinite;
}

.split-stage {
  grid-template-columns: 1.1fr 0.9fr;
  gap: 44px;
  align-items: center;
}

.office-oracle {
  background: #d8d8d8;
  border: 4px solid var(--bb-ink);
  box-shadow: 8px 8px 0 var(--bb-shadow);
  padding: 28px;
}

.oracle-face {
  font-size: 88px;
  text-align: center;
  animation: officeFloat 4s ease-in-out infinite;
}

.speech-bubble {
  background: white;
  border: 3px solid var(--bb-ink);
  padding: 18px;
  font-size: 24px;
}

.slide-subtitle {
  margin: 0 0 24px;
  font-size: 22px;
  background: rgba(255, 255, 255, 0.72);
  border-left: 8px solid var(--bb-pink);
  padding: 12px 16px;
}

.evidence-window {
  margin: 12px 0;
}

.deck-screenshot {
  display: block;
  width: min(100%, 720px);
  max-height: 260px;
  object-fit: contain;
  object-position: top left;
  border: 3px solid var(--bb-ink);
  box-shadow: 5px 5px 0 rgba(23, 17, 41, 0.22);
  background: white;
  margin: 0 0 14px;
}

.journey-screenshot {
  display: block;
  width: min(82%, 620px);
  max-height: 220px;
  object-fit: contain;
  border: 3px solid var(--bb-ink);
  box-shadow: 5px 5px 0 rgba(23, 17, 41, 0.22);
  background: white;
  margin: 10px 0 12px 36px;
}

.window-body {
  position: relative;
  padding: 18px 20px;
}

.sticker {
  position: absolute;
  top: 12px;
  right: 12px;
  background: var(--bb-green);
  transform: rotate(3deg);
}

.evidence {
  color: #50366f;
  font-size: 12px;
}

.promise-stamp {
  margin-right: 10px;
  background: #ff9be8;
  font-size: 13px;
  padding: 3px 7px;
  box-shadow: 2px 2px 0 var(--bb-ink);
}

.sticker-sheet,
.evidence-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.component-sticker {
  background: #fff;
  border: 3px dashed var(--bb-ink);
  box-shadow: 5px 5px 0 var(--bb-shadow);
  padding: 16px;
}

.component-sticker span,
.component-sticker strong {
  display: block;
}

.sticker-emoji {
  font-size: 30px;
}

.empty-desk {
  display: grid;
  place-items: center;
  gap: 8px;
  min-height: 260px;
  background: rgba(255, 252, 232, 0.9);
  border: 4px dotted var(--bb-ink);
  box-shadow: 8px 8px 0 var(--bb-shadow);
  text-align: center;
  padding: 28px;
}

.empty-icon {
  font-size: 64px;
}

.basement-title {
  background: linear-gradient(135deg, #f0e2c0, #8fd3ff);
  text-align: center;
}

.warning-sign {
  font-size: 90px;
  animation: officeFloat 3s ease-in-out infinite;
}

.evidence-grid code {
  display: block;
  overflow-wrap: anywhere;
  background: #111;
  color: #89ffcb;
  border: 2px solid var(--bb-pink);
  padding: 8px;
  font-size: 11px;
}

@keyframes officeFloat {
  0%, 100% { transform: translateY(0) rotate(-2deg); }
  50% { transform: translateY(-10px) rotate(2deg); }
}
</style>`;
}

function humanizeFile(file) {
  const name = file.split("/").at(-1) ?? file;
  const withoutExtension = name.replace(/\.[^.]+$/, "");

  return withoutExtension
    .split(/[-_.]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}

function catchyBehaviorLabel(file) {
  const label = humanizeFile(file);

  if (file.includes("e2e/")) {
    return `${label}: the user promise`;
  }

  return `${label}: the safety net`;
}

function isProto(file) {
  return file.startsWith("proto/") || file.endsWith(".proto");
}

function isDatabase(file) {
  return file.includes("migration") || file.includes("migrations/") || file.endsWith(".sql");
}

function isBehavior(file) {
  return (
    file.startsWith("e2e/") ||
    file.endsWith(".spec.ts") ||
    file.endsWith(".spec.tsx") ||
    file.endsWith(".test.ts") ||
    file.endsWith(".test.tsx")
  );
}

function isDesignSystem(file) {
  return (
    file.includes("design-system") ||
    file.endsWith(".stories.ts") ||
    file.endsWith(".stories.tsx")
  );
}

function isPage(file) {
  if (
    file.endsWith(".stories.ts") ||
    file.endsWith(".stories.tsx") ||
    file.endsWith(".test.ts") ||
    file.endsWith(".test.tsx")
  ) {
    return false;
  }

  return (
    file.includes("/pages/") ||
    file.includes("/routes/") ||
    file.includes("router") ||
    file.includes("route")
  );
}

function isBackend(file) {
  if (isDatabase(file)) {
    return false;
  }

  return file.startsWith("server/") || file.endsWith(".rs");
}
